// Code generated by logcopter-gen; DO NOT EDIT.

package backend

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.plz-confirm.pkg.backend")
