# this is copied over from goreleaser/goreleaser/.github/workflows/lint.yml
name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  golangci:
    permissions:
      contents: read
      pull-requests: read
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: Install golangci-lint with selected Go toolchain
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.4.0
      - name: golangci-lint
        run: golangci-lint run --timeout=5m
